name: Web App CD Pipeline

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: "your-webapp-name"

jobs:
  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Azure Login using Service Principal
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Zip application
      - name: Archive Application
        run: |
          zip -r app.zip .
          

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: app.zip